include:
  - db/compose.yaml

services:
  fe:
    build: ./FE/KettoLingoFE
    restart: always
    ports:
      - '5173:5173'
    environment:
      KETTO_BE: "http://flask:5000"
  flask:
    build: .
    restart: always
    ports:
      - '5000:5000'
    stop_signal: SIGINT
    environment:
      KETTO_DB: "postgresql://postgres:postgres@db/KettoLingo"
      KETTO_FE: "fe"
    depends_on:
      db:
        condition: service_healthy
