"""Add native_language_id to User

Revision ID: 7b36fea9c834
Revises: 065da3fbbbff
Create Date: 2024-11-04 12:56:26.288896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b36fea9c834'
down_revision = '065da3fbbbff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_language_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'languages', ['native_language_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('native_language_id')

    # ### end Alembic commands ###
