services:
  db:
    image: postgres:17.0-alpine
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: KettoLingo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "KettoLingo"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
